QT.dtkcore.VERSION = 5.2.2.2
QT.dtkcore.MAJOR_VERSION = 5
QT.dtkcore.MINOR_VERSION = 2
QT.dtkcore.PATCH_VERSION = 2
QT.dtkcore.name = dtkcore
QT.dtkcore.module = dtkcore
QT.dtkcore.tools = /usr/lib/x86_64-linux-gnu/libdtk-5.2.2/DCore/bin
QT.dtkcore.libs = /usr/lib/x86_64-linux-gnu
QT.dtkcore.includes = /usr/include/libdtk-5.2.2/DCore
QT.dtkcore.frameworks =
QT.dtkcore.depends = core dbus xml
QT.dtkcore.module_config = v2
QT.dtkcore.DEFINES = 
QT_MODULES += 
